config/routes.rb
Rails.application.routes.draw do
  constraints Rodauth::Rails.authenticated do
    namespace :api do
      namespace :v1 do
        resources :documents, only: [:index, :destroy] do
          collection do
            post :prepare
            post :new_upload
          end
        end
      end
    end

    resources :documents, only: :index
  end

  root to: "home#index"
end

app/models/account.rb
class Account < ApplicationRecord
  include Rodauth::Rails.model
  enum :status, unverified: 1, verified: 2, closed: 3

  has_many :documents
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/document.rb
class Document < ApplicationRecord
  belongs_to :account
  before_save :check_filename_presence

  # IMPORTANT, COMMENTED TO MAKE THE TESTING EASIER, UNCOMMENT TO TEST WITH S3
  # before_destroy :delete_content

  def download_url(public = false)
    public ? s3_obj.public_url : presigned_download_url
  end

  def presigned_download_url
    s3_obj.presigned_url(:get, expires_in: 3600)
  end

  def region_name
    @region_name = self.bucket_location || 'us-east-1'
    @region_name = 'eu-west-1' if @region_name == 'EU'

    @region_name
  end

  private

  def s3_obj
    ::Aws::S3::Resource.new(region: region_name, credentials: s3_signer_credentials)
                       .bucket(bucket_name)
                       .object(path)
  end

  def s3_signer_credentials
    secrets = ::Rails.application.secrets.aws_s3_signer
    @s3_signer_credentials ||= ::Aws::Credentials.new(
      secrets[:access_key_id],
      secrets[:secret_access_key]
    )
  end

  def check_filename_presence
    !self.filename.to_s.strip.blank?
  end

  def delete_content
    secrets = ::Rails.application.secrets.aws_s3_signer
    s3_client = ::Aws::S3::Client.new(
      region: self.bucket_location,
      access_key_id: secrets[:access_key_id],
      secret_access_key: secrets[:secret_access_key]
    )
    s3_client.delete_object bucket: self.bucket_name, key: self.path
  rescue Exception => e
    Rails.logger.error "Error during S3 file deletion: #{e.message}"
    Rails.logger.error e.backtrace.join("\n")
  end
end

app/controllers/api/v1/api_controller.rb
class Api::V1::ApiController < ActionController::Base
  skip_before_action :verify_authenticity_token
end

app/controllers/api/v1/documents_controller.rb
class Api::V1::DocumentsController < Api::V1::ApiController
  def index
    render json: current_account.documents.map{|document| DocumentSerializer.serialize(document)}
  end

  def prepare
    s3_form_service = ::Documents::S3FormService.new(current_account)
    ascii_names = {}
    create_file_names_params[:files].to_h.each_value do |file|
      ascii_names[file[:uuid]] = file[:name].to_s.to_ascii unless file[:name].to_s.ascii_only?
    end

    # Permissions for viewing file to private by default
    render json: {
      formData: s3_form_service.s3_form(current_account.id),
      asciiNames: ascii_names
    }
  end

  def new_upload
    new_upload_service = ::Documents::NewUploadService.new(current_account)

    document = new_upload_service.create_document(
      name: new_upload_params[:name],
      key: new_upload_params[:key],
      size: new_upload_params[:size]
    )
    render json: { document: DocumentSerializer.serialize(document) }

  rescue => e # NewUploadService may raise exception for various reasons
    return render :json => { status: :error, message: e.message }, status: 422
  end

  def destroy
    document.destroy
    render json: { status: :ok }, status: 200
  end

  private

  def document
    @document ||= begin
                      raise IdError.new(Document, nil) unless document_id.present?

                      document = current_account.documents.find(document_id)
                      raise IdError.new(Document, document_id) if document.nil?
                      document
                    end
  end

  def document_id
    @document_id ||= document_id_param[:id]
  end

  def document_id_param
    params.permit(:id)
  end

  def new_upload_params
    @new_upload_params_hash ||= params.permit(:name, :size, :key).to_h.symbolize_keys
  end

  def create_file_names_params
    @file_names_params ||= params.permit(files: [:uuid, :name])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/rodauth_controller.rb
class RodauthController < ApplicationController
  # used by Rodauth for rendering views, CSRF protection, and running any
  # registered action callbacks and rescue_from handlers
end

app/helpers/api/v1/documents_helper.rb
module Api::V1::DocumentsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<h1>Welcome to file uploader!</h1>
<div class="lead my-3"><%= link_to "go to documents page", documents_path %></div>

<% if rodauth.logged_in? %>
  <%= link_to "Sign out", rodauth.logout_path, method: :post %>
<% else %>
  <%= link_to "Sign in", rodauth.login_path %>
  <%= link_to "Sign up", rodauth.create_account_path %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FileUploader</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= javascript_pack_tag 'application' %>
    <%= javascript_pack_tag 'index' %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <div class="center-content">
      <%= yield %>
    </div>
  </body>
</html>

app/views/rodauth/_login_form.html.erb
<%= form_with url: rodauth.login_path, method: :post, data: { turbo: false } do |form| %>
  <% if rodauth.skip_login_field_on_login? %>
    <div class="form-group mb-3">
      <%= form.label "login", rodauth.login_label, class: "form-label" %>
      <%= form.email_field rodauth.login_param, value: params[rodauth.login_param], id: "login", readonly: true, class: "form-control-plaintext" %>
    </div>
  <% else %>
    <div class="form-group mb-3">
      <%= form.label "login", rodauth.login_label, class: "form-label" %>
      <%= form.email_field rodauth.login_param, value: params[rodauth.login_param], id: "login", autocomplete: "email", required: true, class: "form-control #{"is-invalid" if rodauth.field_error(rodauth.login_param)}", aria: ({ invalid: true, describedby: "login_error_message" } if rodauth.field_error(rodauth.login_param)) %>
      <%= content_tag(:span, rodauth.field_error(rodauth.login_param), class: "invalid-feedback", id: "login_error_message") if rodauth.field_error(rodauth.login_param) %>
    </div>
  <% end %>

  <% unless rodauth.skip_password_field_on_login? %>
    <div class="form-group mb-3">
      <%= form.label "password", rodauth.password_label, class: "form-label" %>
      <%= form.password_field rodauth.password_param, value: "", id: "password", autocomplete: rodauth.password_field_autocomplete_value, required: true, class: "form-control #{"is-invalid" if rodauth.field_error(rodauth.password_param)}", aria: ({ invalid: true, describedby: "password_error_message" } if rodauth.field_error(rodauth.password_param)) %>
      <%= content_tag(:span, rodauth.field_error(rodauth.password_param), class: "invalid-feedback", id: "password_error_message") if rodauth.field_error(rodauth.password_param) %>
    </div>
  <% end %>

  <div class="form-group mb-3">
    <%= form.submit rodauth.login_button, class: "btn btn-primary login-button" %>
  </div>
<% end %>

app/views/rodauth/_login_form_footer.html.erb
<% unless rodauth.login_form_footer_links.empty? %>
  <%== rodauth.login_form_footer_links_heading %>

  <ul>
    <% rodauth.login_form_footer_links.sort.each do |_, link, text| %>
      <li><%= link_to text, link %></li>
    <% end %>
  </ul>
<% end %>

app/views/rodauth/_login_form_header.html.erb
<% if rodauth.field_error(rodauth.password_param) && rodauth.features.include?(:reset_password) %>
  <%= render template: "rodauth/reset_password_request", layout: false %>
<% end %>

app/views/rodauth/change_login.html.erb
<% content_for :title, rodauth.change_login_page_title %>

<%= form_with url: rodauth.change_login_path, method: :post, data: { turbo: false } do |form| %>
  <div class="form-group mb-3">
    <%= form.label "login", rodauth.login_label, class: "form-label" %>
    <%= form.email_field rodauth.login_param, value: params[rodauth.login_param], id: "login", autocomplete: "email", required: true, class: "form-control #{"is-invalid" if rodauth.field_error(rodauth.login_param)}", aria: ({ invalid: true, describedby: "login_error_message" } if rodauth.field_error(rodauth.login_param)) %>
    <%= content_tag(:span, rodauth.field_error(rodauth.login_param), class: "invalid-feedback", id: "login_error_message") if rodauth.field_error(rodauth.login_param) %>
  </div>

  <% if rodauth.require_login_confirmation? %>
    <div class="form-group mb-3">
      <%= form.label "login-confirm", rodauth.login_confirm_label, class: "form-label" %>
      <%= form.email_field rodauth.login_confirm_param, value: params[rodauth.login_confirm_param], id: "login-confirm", autocomplete: "email", required: true, class: "form-control #{"is-invalid" if rodauth.field_error(rodauth.login_confirm_param)}", aria: ({ invalid: true, describedby: "login-confirm_error_message" } if rodauth.field_error(rodauth.login_confirm_param)) %>
      <%= content_tag(:span, rodauth.field_error(rodauth.login_confirm_param), class: "invalid-feedback", id: "login-confirm_error_message") if rodauth.field_error(rodauth.login_confirm_param) %>
    </div>
  <% end %>

  <% if rodauth.change_login_requires_password? %>
    <div class="form-group mb-3">
      <%= form.label "password", rodauth.password_label, class: "form-label" %>
      <%= form.password_field rodauth.password_param, value: "", id: "password", autocomplete: rodauth.password_field_autocomplete_value, required: true, class: "form-control #{"is-invalid" if rodauth.field_error(rodauth.password_param)}", aria: ({ invalid: true, describedby: "password_error_message" } if rodauth.field_error(rodauth.password_param)) %>
      <%= content_tag(:span, rodauth.field_error(rodauth.password_param), class: "invalid-feedback", id: "password_error_message") if rodauth.field_error(rodauth.password_param) %>
    </div>
  <% end %>

  <div class="form-group mb-3">
    <%= form.submit rodauth.change_login_button, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/rodauth/close_account.html.erb
<% content_for :title, rodauth.close_account_page_title %>

<%= form_with url: rodauth.close_account_path, method: :post, data: { turbo: false } do |form| %>
  <% if rodauth.close_account_requires_password? %>
    <div class="form-group mb-3">
      <%= form.label "password", rodauth.password_label, class: "form-label" %>
      <%= form.password_field rodauth.password_param, value: "", id: "password", autocomplete: rodauth.password_field_autocomplete_value, required: true, class: "form-control #{"is-invalid" if rodauth.field_error(rodauth.password_param)}", aria: ({ invalid: true, describedby: "password_error_message" } if rodauth.field_error(rodauth.password_param)) %>
      <%= content_tag(:span, rodauth.field_error(rodauth.password_param), class: "invalid-feedback", id: "password_error_message") if rodauth.field_error(rodauth.password_param) %>
    </div>
  <% end %>

  <div class="form-group mb-3">
    <%= form.submit rodauth.close_account_button, class: "btn btn-danger" %>
  </div>
<% end %>

app/views/rodauth/create_account.html.erb
<% content_for :title, rodauth.create_account_page_title %>

<%= form_with url: rodauth.create_account_path, method: :post, data: { turbo: false } do |form| %>
  <div class="form-group mb-3">
    <%= form.label "login", rodauth.login_label, class: "form-label" %>
    <%= form.email_field rodauth.login_param, value: params[rodauth.login_param], id: "login", autocomplete: "email", required: true, class: "form-control #{"is-invalid" if rodauth.field_error(rodauth.login_param)}", aria: ({ invalid: true, describedby: "login_error_message" } if rodauth.field_error(rodauth.login_param)) %>
    <%= content_tag(:span, rodauth.field_error(rodauth.login_param), class: "invalid-feedback", id: "login_error_message") if rodauth.field_error(rodauth.login_param) %>
  </div>

  <% if rodauth.require_login_confirmation? %>
    <div class="form-group mb-3">
      <%= form.label "login-confirm", rodauth.login_confirm_label, class: "form-label" %>
      <%= form.email_field rodauth.login_confirm_param, value: params[rodauth.login_confirm_param], id: "login-confirm", autocomplete: "email", required: true, class: "form-control #{"is-invalid" if rodauth.field_error(rodauth.login_confirm_param)}", aria: ({ invalid: true, describedby: "login-confirm_error_message" } if rodauth.field_error(rodauth.login_confirm_param)) %>
      <%= content_tag(:span, rodauth.field_error(rodauth.login_confirm_param), class: "invalid-feedback", id: "login-confirm_error_message") if rodauth.field_error(rodauth.login_confirm_param) %>
    </div>
  <% end %>

  <% if rodauth.create_account_set_password? %>
    <div class="form-group mb-3">
      <%= form.label "password", rodauth.password_label, class: "form-label" %>
      <%= form.password_field rodauth.password_param, value: "", id: "password", autocomplete: rodauth.password_field_autocomplete_value, required: true, class: "form-control #{"is-invalid" if rodauth.field_error(rodauth.password_param)}", aria: ({ invalid: true, describedby: "password_error_message" } if rodauth.field_error(rodauth.password_param)) %>
      <%= content_tag(:span, rodauth.field_error(rodauth.password_param), class: "invalid-feedback", id: "password_error_message") if rodauth.field_error(rodauth.password_param) %>
    </div>

    <% if rodauth.require_password_confirmation? %>
      <div class="form-group mb-3">
        <%= form.label "password-confirm", rodauth.password_confirm_label, class: "form-label" %>
        <%= form.password_field rodauth.password_confirm_param, value: "", id: "password-confirm", autocomplete: "new-password", required: true, class: "form-control #{"is-invalid" if rodauth.field_error(rodauth.password_confirm_param)}", aria: ({ invalid: true, describedby: "password-confirm_error_message" } if rodauth.field_error(rodauth.password_confirm_param)) %>
        <%= content_tag(:span, rodauth.field_error(rodauth.password_confirm_param), class: "invalid-feedback", id: "password-confirm_error_message") if rodauth.field_error(rodauth.password_confirm_param) %>
      </div>
    <% end %>
  <% end %>

  <div class="form-group mb-3">
    <%= form.submit rodauth.create_account_button, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/rodauth/login.html.erb
<% content_for :title, rodauth.login_page_title %>

<%= render "login_form_header" %>
<%= render "login_form" %>
<%= render "login_form_footer" %>

app/views/rodauth/logout.html.erb
<% content_for :title, rodauth.logout_page_title %>

<%= form_with url: rodauth.logout_path, method: :post, data: { turbo: false } do |form| %>
  <% if rodauth.features.include?(:active_sessions) %>
    <div class="form-group mb-3">
      <div class="form-check">
        <%= form.check_box rodauth.global_logout_param, id: "global-logout", class: "form-check-input" %>
        <%= form.label "global-logout", rodauth.global_logout_label, class: "form-check-label" %>
      </div>
    </div>
  <% end %>

  <div class="form-group mb-3">
    <%= form.submit rodauth.logout_button, class: "btn btn-warning" %>
  </div>
<% end %>

app/views/rodauth/multi_phase_login.html.erb
<% content_for :title, rodauth.multi_phase_login_page_title %>

<%= render "login_form_header" %>
<%== rodauth.render_multi_phase_login_forms %>
<%= render "login_form_footer" %>

app/views/rodauth/remember.html.erb
<% content_for :title, rodauth.remember_page_title %>

<%= form_with url: rodauth.remember_path, method: :post, data: { turbo: false } do |form| %>
  <fieldset class="form-group mb-3">
    <div class="form-check">
      <%= form.radio_button rodauth.remember_param, rodauth.remember_remember_param_value, id: "remember-remember", class: "form-check-input" %>
      <%= form.label "remember-remember", rodauth.remember_remember_label, class: "form-check-label" %>
    </div>

    <div class="form-check">
      <%= form.radio_button rodauth.remember_param, rodauth.remember_forget_param_value, id: "remember-forget", class: "form-check-input" %>
      <%= form.label "remember-forget", rodauth.remember_forget_label, class: "form-check-label" %>
    </div>

    <div class="form-check">
      <%= form.radio_button rodauth.remember_param, rodauth.remember_disable_param_value, id: "remember-disable", class: "form-check-input" %>
      <%= form.label "remember-disable", rodauth.remember_disable_label, class: "form-check-label" %>
    </div>
  </fieldset>

  <div class="form-group mb-3">
    <%= form.submit rodauth.remember_button, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/rodauth/reset_password.html.erb
<% content_for :title, rodauth.reset_password_page_title %>

<%= form_with url: rodauth.reset_password_path, method: :post, data: { turbo: false } do |form| %>
  <div class="form-group mb-3">
    <%= form.label "password", rodauth.password_label, class: "form-label" %>
    <%= form.password_field rodauth.password_param, value: "", id: "password", autocomplete: rodauth.password_field_autocomplete_value, required: true, class: "form-control #{"is-invalid" if rodauth.field_error(rodauth.password_param)}", aria: ({ invalid: true, describedby: "password_error_message" } if rodauth.field_error(rodauth.password_param)) %>
    <%= content_tag(:span, rodauth.field_error(rodauth.password_param), class: "invalid-feedback", id: "password_error_message") if rodauth.field_error(rodauth.password_param) %>
  </div>

  <% if rodauth.require_password_confirmation? %>
    <div class="form-group mb-3">
      <%= form.label "password-confirm", rodauth.password_confirm_label, class: "form-label" %>
      <%= form.password_field rodauth.password_confirm_param, value: "", id: "password-confirm", autocomplete: "new-password", required: true, class: "form-control #{"is-invalid" if rodauth.field_error(rodauth.password_confirm_param)}", aria: ({ invalid: true, describedby: "password-confirm_error_message" } if rodauth.field_error(rodauth.password_confirm_param)) %>
      <%= content_tag(:span, rodauth.field_error(rodauth.password_confirm_param), class: "invalid-feedback", id: "password-confirm_error_message") if rodauth.field_error(rodauth.password_confirm_param) %>
    </div>
  <% end %>

  <div class="form-group mb-3">
    <%= form.submit rodauth.reset_password_button, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/rodauth/reset_password_request.html.erb
<% content_for :title, rodauth.reset_password_request_page_title %>

<%= form_with url: rodauth.reset_password_request_path, method: :post, data: { turbo: false } do |form| %>
  <%== rodauth.reset_password_explanatory_text %>

  <% if params[rodauth.login_param] && !rodauth.field_error(rodauth.login_param) %>
    <%= form.hidden_field rodauth.login_param, value: params[rodauth.login_param] %>
  <% else %>
    <div class="form-group mb-3">
      <%= form.label "login", rodauth.login_label, class: "form-label" %>
      <%= form.email_field rodauth.login_param, value: params[rodauth.login_param], id: "login", autocomplete: "email", required: true, class: "form-control #{"is-invalid" if rodauth.field_error(rodauth.login_param)}", aria: ({ invalid: true, describedby: "login_error_message" } if rodauth.field_error(rodauth.login_param)) %>
      <%= content_tag(:span, rodauth.field_error(rodauth.login_param), class: "invalid-feedback", id: "login_error_message") if rodauth.field_error(rodauth.login_param) %>
    </div>
  <% end %>

  <div class="form-group mb-3">
    <%= form.submit rodauth.reset_password_request_button, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/rodauth/verify_account.html.erb
<% content_for :title, rodauth.verify_account_page_title %>

<%= form_with url: rodauth.verify_account_path, method: :post, data: { turbo: false } do |form| %>
  <% if rodauth.verify_account_set_password? %>
    <div class="form-group mb-3">
      <%= form.label "password", rodauth.password_label, class: "form-label" %>
      <%= form.password_field rodauth.password_param, value: "", id: "password", autocomplete: rodauth.password_field_autocomplete_value, required: true, class: "form-control #{"is-invalid" if rodauth.field_error(rodauth.password_param)}", aria: ({ invalid: true, describedby: "password_error_message" } if rodauth.field_error(rodauth.password_param)) %>
      <%= content_tag(:span, rodauth.field_error(rodauth.password_param), class: "invalid-feedback", id: "password_error_message") if rodauth.field_error(rodauth.password_param) %>
    </div>

    <% if rodauth.require_password_confirmation? %>
      <div class="form-group mb-3">
        <%= form.label "password-confirm", rodauth.password_confirm_label, class: "form-label" %>
        <%= form.password_field rodauth.password_confirm_param, value: "", id: "password-confirm", autocomplete: "new-password", required: true, class: "form-control #{"is-invalid" if rodauth.field_error(rodauth.password_confirm_param)}", aria: ({ invalid: true, describedby: "password-confirm_error_message" } if rodauth.field_error(rodauth.password_confirm_param)) %>
        <%= content_tag(:span, rodauth.field_error(rodauth.password_confirm_param), class: "invalid-feedback", id: "password-confirm_error_message") if rodauth.field_error(rodauth.password_confirm_param) %>
      </div>
    <% end %>
  <% end %>

  <div class="form-group mb-3">
    <%= form.submit rodauth.verify_account_button, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/rodauth/verify_login_change.html.erb
<% content_for :title, rodauth.verify_login_change_page_title %>

<%= form_with url: rodauth.verify_login_change_path, method: :post, data: { turbo: false } do |form| %>
  <div class="form-group mb-3">
    <%= form.submit rodauth.verify_login_change_button, class: "btn btn-primary" %>
  </div>
<% end %>